import type { Metadata } from "next";

import ReactQueryProviders from "@/app/root/react-query-provider";

import "../styles/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className="mx-auto max-w-7xl bg-gray-100">
        <ReactQueryProviders>{children}</ReactQueryProviders>
      </body>
    </html>
  );
}
